/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CameraNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CameraNotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "take-picture-and-insert",
      name: "Take Picture and Insert",
      editorCallback: (editor, ctx) => {
        new CameraModal(this.app, editor, ctx.file || null).open();
      }
    });
  }
};
var CameraModal = class extends import_obsidian.Modal {
  constructor(app, editor, file) {
    super(app);
    __publicField(this, "editor");
    __publicField(this, "file");
    __publicField(this, "videoEl");
    __publicField(this, "canvasEl");
    __publicField(this, "overlayCanvasEl");
    __publicField(this, "stream", null);
    __publicField(this, "captureBtn");
    __publicField(this, "saveBtn");
    __publicField(this, "isCropping", false);
    __publicField(this, "cropStartX", 0);
    __publicField(this, "cropStartY", 0);
    __publicField(this, "cropWidth", 0);
    __publicField(this, "cropHeight", 0);
    __publicField(this, "isDragging", false);
    this.editor = editor;
    this.file = file;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.classList.add("camera-note-modal");
    contentEl.createEl("h2", { text: "Take a Picture" });
    const container = contentEl.createDiv({ cls: "camera-container" });
    this.canvasEl = container.createEl("canvas", { cls: "hidden" });
    this.overlayCanvasEl = container.createEl("canvas", { cls: "hidden overlay-canvas" });
    const controls = contentEl.createDiv({ cls: "camera-controls" });
    this.saveBtn = controls.createEl("button", { text: "Crop & Save", cls: "hidden mod-cta" });
    this.saveBtn.addEventListener("click", () => this.saveImage());
    this.setupCroppingEvents();
    if (import_obsidian.Platform.isMobile) {
      this.captureBtn = controls.createEl("button", { text: "Take Photo" });
      const fileInput = contentEl.createEl("input");
      fileInput.type = "file";
      fileInput.accept = "image/*";
      fileInput.capture = "environment";
      fileInput.style.display = "none";
      fileInput.addEventListener("change", () => this.handleFileCapture(fileInput));
      this.captureBtn.addEventListener("click", () => fileInput.click());
    } else {
      this.videoEl = container.createEl("video");
      this.videoEl.autoplay = true;
      this.videoEl.playsInline = true;
      this.captureBtn = controls.createEl("button", { text: "Capture" });
      this.captureBtn.addEventListener("click", () => this.captureImage());
      this.startCamera();
    }
  }
  async startCamera() {
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } });
      this.videoEl.srcObject = this.stream;
    } catch (err) {
      new import_obsidian.Notice("Error accessing camera: " + (err.message || err.toString()));
    }
  }
  captureImage() {
    if (!this.videoEl.videoWidth) return;
    this.canvasEl.width = this.videoEl.videoWidth;
    this.canvasEl.height = this.videoEl.videoHeight;
    this.overlayCanvasEl.width = this.videoEl.videoWidth;
    this.overlayCanvasEl.height = this.videoEl.videoHeight;
    const ctx = this.canvasEl.getContext("2d");
    if (ctx) {
      ctx.drawImage(this.videoEl, 0, 0, this.canvasEl.width, this.canvasEl.height);
    }
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
    }
    this.videoEl.classList.add("hidden");
    this.canvasEl.classList.remove("hidden");
    this.overlayCanvasEl.classList.remove("hidden");
    this.captureBtn.classList.add("hidden");
    this.saveBtn.classList.remove("hidden");
    this.cropWidth = this.canvasEl.width;
    this.cropHeight = this.canvasEl.height;
    this.isCropping = true;
    this.drawOverlay();
  }
  handleFileCapture(fileInput) {
    const file = fileInput.files && fileInput.files[0];
    if (!file) return;
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      this.canvasEl.width = img.naturalWidth;
      this.canvasEl.height = img.naturalHeight;
      this.overlayCanvasEl.width = img.naturalWidth;
      this.overlayCanvasEl.height = img.naturalHeight;
      const ctx = this.canvasEl.getContext("2d");
      if (ctx) ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      this.canvasEl.classList.remove("hidden");
      this.overlayCanvasEl.classList.remove("hidden");
      this.captureBtn.classList.add("hidden");
      this.saveBtn.classList.remove("hidden");
      this.cropWidth = this.canvasEl.width;
      this.cropHeight = this.canvasEl.height;
      this.isCropping = true;
      this.drawOverlay();
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      new import_obsidian.Notice("Failed to load captured image.");
    };
    img.src = url;
  }
  setupCroppingEvents() {
    this.overlayCanvasEl.addEventListener("mousedown", (e) => {
      if (!this.isCropping) return;
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      this.cropStartX = (e.clientX - rect.left) * scaleX;
      this.cropStartY = (e.clientY - rect.top) * scaleY;
      this.cropWidth = 0;
      this.cropHeight = 0;
      this.isDragging = true;
    });
    this.overlayCanvasEl.addEventListener("mousemove", (e) => {
      if (!this.isDragging) return;
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      const currentX = (e.clientX - rect.left) * scaleX;
      const currentY = (e.clientY - rect.top) * scaleY;
      this.cropWidth = currentX - this.cropStartX;
      this.cropHeight = currentY - this.cropStartY;
      this.drawOverlay();
    });
    this.overlayCanvasEl.addEventListener("mouseup", (e) => {
      this.isDragging = false;
      if (this.cropWidth < 0) {
        this.cropStartX += this.cropWidth;
        this.cropWidth = Math.abs(this.cropWidth);
      }
      if (this.cropHeight < 0) {
        this.cropStartY += this.cropHeight;
        this.cropHeight = Math.abs(this.cropHeight);
      }
    });
    this.overlayCanvasEl.addEventListener("touchstart", (e) => {
      if (!this.isCropping) return;
      e.preventDefault();
      const touch = e.touches[0];
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      this.cropStartX = (touch.clientX - rect.left) * scaleX;
      this.cropStartY = (touch.clientY - rect.top) * scaleY;
      this.cropWidth = 0;
      this.cropHeight = 0;
      this.isDragging = true;
    }, { passive: false });
    this.overlayCanvasEl.addEventListener("touchmove", (e) => {
      if (!this.isDragging) return;
      e.preventDefault();
      const touch = e.touches[0];
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      const currentX = (touch.clientX - rect.left) * scaleX;
      const currentY = (touch.clientY - rect.top) * scaleY;
      this.cropWidth = currentX - this.cropStartX;
      this.cropHeight = currentY - this.cropStartY;
      this.drawOverlay();
    }, { passive: false });
    this.overlayCanvasEl.addEventListener("touchend", (e) => {
      this.isDragging = false;
      if (this.cropWidth < 0) {
        this.cropStartX += this.cropWidth;
        this.cropWidth = Math.abs(this.cropWidth);
      }
      if (this.cropHeight < 0) {
        this.cropStartY += this.cropHeight;
        this.cropHeight = Math.abs(this.cropHeight);
      }
    });
  }
  drawOverlay() {
    const ctx = this.overlayCanvasEl.getContext("2d");
    if (!ctx) return;
    ctx.clearRect(0, 0, this.overlayCanvasEl.width, this.overlayCanvasEl.height);
    ctx.fillStyle = "rgba(0, 0, 0, 0.5)";
    ctx.fillRect(0, 0, this.overlayCanvasEl.width, this.overlayCanvasEl.height);
    ctx.clearRect(this.cropStartX, this.cropStartY, this.cropWidth, this.cropHeight);
    ctx.strokeStyle = "#00aaff";
    ctx.lineWidth = 2;
    ctx.strokeRect(this.cropStartX, this.cropStartY, this.cropWidth, this.cropHeight);
  }
  async saveImage() {
    if (this.cropWidth === 0 || this.cropHeight === 0) {
      new import_obsidian.Notice("Please select an area to crop.");
      return;
    }
    const tempCanvas = document.createElement("canvas");
    tempCanvas.width = this.cropWidth;
    tempCanvas.height = this.cropHeight;
    const tempCtx = tempCanvas.getContext("2d");
    if (tempCtx) {
      tempCtx.drawImage(
        this.canvasEl,
        this.cropStartX,
        this.cropStartY,
        this.cropWidth,
        this.cropHeight,
        0,
        0,
        this.cropWidth,
        this.cropHeight
      );
    }
    tempCanvas.toBlob((blob) => {
      if (!blob) {
        new import_obsidian.Notice("Failed to generate image.");
        return;
      }
      blob.arrayBuffer().then(async (arrayBuffer) => {
        let folderPath = "images";
        if (this.file && this.file.parent) {
          const parentPath = this.file.parent.path;
          folderPath = parentPath === "/" ? "images" : `${parentPath}/images`;
        }
        const folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
          await this.app.vault.createFolder(folderPath);
        }
        const now = /* @__PURE__ */ new Date();
        const yyyy = now.getFullYear();
        const mm = String(now.getMonth() + 1).padStart(2, "0");
        const dd = String(now.getDate()).padStart(2, "0");
        const hh = String(now.getHours()).padStart(2, "0");
        const min = String(now.getMinutes()).padStart(2, "0");
        const ss = String(now.getSeconds()).padStart(2, "0");
        const filename = `camera-${yyyy}${mm}${dd}-${hh}${min}${ss}.jpg`;
        const filePath = `${folderPath}/${filename}`;
        await this.app.vault.createBinary(filePath, arrayBuffer);
        this.editor.replaceSelection(`![[${filename}]]`);
        new import_obsidian.Notice("Image saved and inserted!");
        this.close();
      }).catch((err) => {
        new import_obsidian.Notice("Error saving image: " + (err.message || err.toString()));
      });
    }, "image/jpeg", 0.9);
  }
  onClose() {
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
    }
    this.contentEl.empty();
  }
};
