/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CameraNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CameraNotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "take-picture-and-insert",
      name: "Take Picture and Insert",
      editorCallback: (editor, ctx) => {
        new CameraModal(this.app, editor, ctx.file || null).open();
      }
    });
    this.addCommand({
      id: "pdf-sketch-and-insert",
      name: "PDF Sketch and Insert",
      editorCallback: (editor, ctx) => {
        new PDFSketchModal(this.app, editor, ctx.file || null).open();
      }
    });
  }
};

// ── Camera Modal ─────────────────────────────────────────────────────────────

var CameraModal = class extends import_obsidian.Modal {
  constructor(app, editor, file) {
    super(app);
    __publicField(this, "editor");
    __publicField(this, "file");
    __publicField(this, "videoEl");
    __publicField(this, "canvasEl");
    __publicField(this, "overlayCanvasEl");
    __publicField(this, "stream", null);
    __publicField(this, "captureBtn");
    __publicField(this, "saveBtn");
    __publicField(this, "isCropping", false);
    __publicField(this, "cropStartX", 0);
    __publicField(this, "cropStartY", 0);
    __publicField(this, "cropWidth", 0);
    __publicField(this, "cropHeight", 0);
    __publicField(this, "isDragging", false);
    this.editor = editor;
    this.file = file;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.classList.add("camera-note-modal");
    contentEl.createEl("h2", { text: "Take a Picture" });
    const container = contentEl.createDiv({ cls: "camera-container" });
    this.canvasEl = container.createEl("canvas", { cls: "hidden" });
    this.overlayCanvasEl = container.createEl("canvas", { cls: "hidden overlay-canvas" });
    const controls = contentEl.createDiv({ cls: "camera-controls" });
    this.saveBtn = controls.createEl("button", { text: "Crop & Save", cls: "hidden mod-cta" });
    this.saveBtn.addEventListener("click", () => this.saveImage());
    this.setupCroppingEvents();
    if (import_obsidian.Platform.isMobile) {
      this.captureBtn = controls.createEl("button", { text: "Take Photo" });
      const fileInput = contentEl.createEl("input", {
        attr: { type: "file", accept: "image/*", capture: "environment" }
      });
      fileInput.style.display = "none";
      fileInput.addEventListener("change", () => this.handleFileCapture(fileInput));
      this.captureBtn.addEventListener("click", () => fileInput.click());
    } else {
      this.videoEl = container.createEl("video");
      this.videoEl.autoplay = true;
      this.videoEl.playsInline = true;
      this.captureBtn = controls.createEl("button", { text: "Capture" });
      this.captureBtn.addEventListener("click", () => this.captureImage());
      this.startCamera();
    }
  }
  async startCamera() {
    try {
      this.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } });
      this.videoEl.srcObject = this.stream;
    } catch (err) {
      new import_obsidian.Notice("Error accessing camera: " + (err.message || err.toString()));
    }
  }
  captureImage() {
    if (!this.videoEl.videoWidth) return;
    this.canvasEl.width = this.videoEl.videoWidth;
    this.canvasEl.height = this.videoEl.videoHeight;
    this.overlayCanvasEl.width = this.videoEl.videoWidth;
    this.overlayCanvasEl.height = this.videoEl.videoHeight;
    const ctx = this.canvasEl.getContext("2d");
    if (ctx) {
      ctx.drawImage(this.videoEl, 0, 0, this.canvasEl.width, this.canvasEl.height);
    }
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
    }
    this.videoEl.classList.add("hidden");
    this.canvasEl.classList.remove("hidden");
    this.overlayCanvasEl.classList.remove("hidden");
    this.captureBtn.classList.add("hidden");
    this.saveBtn.classList.remove("hidden");
    this.cropWidth = this.canvasEl.width;
    this.cropHeight = this.canvasEl.height;
    this.isCropping = true;
    this.drawOverlay();
  }
  handleFileCapture(fileInput) {
    const file = fileInput.files && fileInput.files[0];
    if (!file) return;
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      this.canvasEl.width = img.naturalWidth;
      this.canvasEl.height = img.naturalHeight;
      this.overlayCanvasEl.width = img.naturalWidth;
      this.overlayCanvasEl.height = img.naturalHeight;
      const ctx = this.canvasEl.getContext("2d");
      if (ctx) ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      this.canvasEl.classList.remove("hidden");
      this.overlayCanvasEl.classList.remove("hidden");
      this.captureBtn.classList.add("hidden");
      this.saveBtn.classList.remove("hidden");
      this.cropWidth = this.canvasEl.width;
      this.cropHeight = this.canvasEl.height;
      this.isCropping = true;
      this.drawOverlay();
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      new import_obsidian.Notice("Failed to load captured image.");
    };
    img.src = url;
  }
  setupCroppingEvents() {
    this.overlayCanvasEl.addEventListener("mousedown", (e) => {
      if (!this.isCropping) return;
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      this.cropStartX = (e.clientX - rect.left) * scaleX;
      this.cropStartY = (e.clientY - rect.top) * scaleY;
      this.cropWidth = 0;
      this.cropHeight = 0;
      this.isDragging = true;
    });
    this.overlayCanvasEl.addEventListener("mousemove", (e) => {
      if (!this.isDragging) return;
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      const currentX = (e.clientX - rect.left) * scaleX;
      const currentY = (e.clientY - rect.top) * scaleY;
      this.cropWidth = currentX - this.cropStartX;
      this.cropHeight = currentY - this.cropStartY;
      this.drawOverlay();
    });
    this.overlayCanvasEl.addEventListener("mouseup", (e) => {
      this.isDragging = false;
      if (this.cropWidth < 0) {
        this.cropStartX += this.cropWidth;
        this.cropWidth = Math.abs(this.cropWidth);
      }
      if (this.cropHeight < 0) {
        this.cropStartY += this.cropHeight;
        this.cropHeight = Math.abs(this.cropHeight);
      }
    });
    this.overlayCanvasEl.addEventListener("touchstart", (e) => {
      if (!this.isCropping) return;
      e.preventDefault();
      const touch = e.touches[0];
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      this.cropStartX = (touch.clientX - rect.left) * scaleX;
      this.cropStartY = (touch.clientY - rect.top) * scaleY;
      this.cropWidth = 0;
      this.cropHeight = 0;
      this.isDragging = true;
    }, { passive: false });
    this.overlayCanvasEl.addEventListener("touchmove", (e) => {
      if (!this.isDragging) return;
      e.preventDefault();
      const touch = e.touches[0];
      const rect = this.overlayCanvasEl.getBoundingClientRect();
      const scaleX = this.overlayCanvasEl.width / rect.width;
      const scaleY = this.overlayCanvasEl.height / rect.height;
      const currentX = (touch.clientX - rect.left) * scaleX;
      const currentY = (touch.clientY - rect.top) * scaleY;
      this.cropWidth = currentX - this.cropStartX;
      this.cropHeight = currentY - this.cropStartY;
      this.drawOverlay();
    }, { passive: false });
    this.overlayCanvasEl.addEventListener("touchend", (e) => {
      this.isDragging = false;
      if (this.cropWidth < 0) {
        this.cropStartX += this.cropWidth;
        this.cropWidth = Math.abs(this.cropWidth);
      }
      if (this.cropHeight < 0) {
        this.cropStartY += this.cropHeight;
        this.cropHeight = Math.abs(this.cropHeight);
      }
    });
  }
  drawOverlay() {
    const ctx = this.overlayCanvasEl.getContext("2d");
    if (!ctx) return;
    ctx.clearRect(0, 0, this.overlayCanvasEl.width, this.overlayCanvasEl.height);
    ctx.fillStyle = "rgba(0, 0, 0, 0.5)";
    ctx.fillRect(0, 0, this.overlayCanvasEl.width, this.overlayCanvasEl.height);
    ctx.clearRect(this.cropStartX, this.cropStartY, this.cropWidth, this.cropHeight);
    ctx.strokeStyle = "#00aaff";
    ctx.lineWidth = 2;
    ctx.strokeRect(this.cropStartX, this.cropStartY, this.cropWidth, this.cropHeight);
  }
  async saveImage() {
    if (this.cropWidth === 0 || this.cropHeight === 0) {
      new import_obsidian.Notice("Please select an area to crop.");
      return;
    }
    const tempCanvas = document.createElement("canvas");
    tempCanvas.width = this.cropWidth;
    tempCanvas.height = this.cropHeight;
    const tempCtx = tempCanvas.getContext("2d");
    if (tempCtx) {
      tempCtx.drawImage(
        this.canvasEl,
        this.cropStartX,
        this.cropStartY,
        this.cropWidth,
        this.cropHeight,
        0,
        0,
        this.cropWidth,
        this.cropHeight
      );
    }
    tempCanvas.toBlob((blob) => {
      if (!blob) {
        new import_obsidian.Notice("Failed to generate image.");
        return;
      }
      blob.arrayBuffer().then(async (arrayBuffer) => {
        let folderPath = "images";
        if (this.file && this.file.parent) {
          const parentPath = this.file.parent.path;
          folderPath = parentPath === "/" ? "images" : `${parentPath}/images`;
        }
        const folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
          await this.app.vault.createFolder(folderPath);
        }
        const now = /* @__PURE__ */ new Date();
        const yyyy = now.getFullYear();
        const mm = String(now.getMonth() + 1).padStart(2, "0");
        const dd = String(now.getDate()).padStart(2, "0");
        const hh = String(now.getHours()).padStart(2, "0");
        const min = String(now.getMinutes()).padStart(2, "0");
        const ss = String(now.getSeconds()).padStart(2, "0");
        const filename = `camera-${yyyy}${mm}${dd}-${hh}${min}${ss}.jpg`;
        const filePath = `${folderPath}/${filename}`;
        await this.app.vault.createBinary(filePath, arrayBuffer);
        this.editor.replaceSelection(`![[${filename}]]`);
        new import_obsidian.Notice("Image saved and inserted!");
        this.close();
      }).catch((err) => {
        new import_obsidian.Notice("Error saving image: " + (err.message || err.toString()));
      });
    }, "image/jpeg", 0.9);
  }
  onClose() {
    if (this.stream) {
      this.stream.getTracks().forEach((track) => track.stop());
    }
    this.contentEl.empty();
  }
};

// ── PDF Sketch Modal ──────────────────────────────────────────────────────────

var PDFJS_CDN = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";
var PDFJS_WORKER_CDN = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
var PDFLIB_CDN = "https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js";

var PDFSketchModal = class extends import_obsidian.Modal {
  constructor(app, editor, file) {
    super(app);
    __publicField(this, "editor");
    __publicField(this, "file");
    // PDF state
    __publicField(this, "pdfDoc", null);
    __publicField(this, "currentPage", 1);
    __publicField(this, "totalPages", 0);
    // Canvas elements
    __publicField(this, "bgCanvas");
    __publicField(this, "drawCanvas");
    __publicField(this, "pageInfoEl");
    __publicField(this, "pageNavEl");
    // Drawing state
    __publicField(this, "isDrawing", false);
    __publicField(this, "currentTool", "pen");
    __publicField(this, "currentColor", "#000000");
    __publicField(this, "lineWidth", 3);
    __publicField(this, "lastX", 0);
    __publicField(this, "lastY", 0);
    // Loaded PDF TFile (for overwrite)
    __publicField(this, "currentPdfFile", null);
    __publicField(this, "saveBtn", null);
    this.editor = editor;
    this.file = file;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.classList.add("camera-note-modal", "pdf-sketch-modal");
    contentEl.createEl("h2", { text: "PDF Sketch" });

    // ── PDF loader ────────────────────────────────────────────────────────────
    const loaderRow = contentEl.createDiv({ cls: "pdf-sketch-loader" });

    const pdfSelect = loaderRow.createEl("select", { cls: "pdf-sketch-select" });
    pdfSelect.createEl("option", { value: "", text: "-- Select a PDF from vault --" });
    const pdfFiles = this.app.vault.getFiles().filter((f) => f.extension === "pdf");
    for (const pf of pdfFiles) {
      pdfSelect.createEl("option", { value: pf.path, text: pf.path });
    }

    const loadBtn = loaderRow.createEl("button", { text: "Load PDF" });

    // ── Page navigation ───────────────────────────────────────────────────────
    this.pageNavEl = contentEl.createDiv({ cls: "pdf-sketch-page-nav hidden" });
    const prevBtn = this.pageNavEl.createEl("button", { text: "← Prev", cls: "pdf-sketch-nav-btn" });
    this.pageInfoEl = this.pageNavEl.createEl("span", { cls: "pdf-sketch-page-info", text: "Page 1 / 1" });
    const nextBtn = this.pageNavEl.createEl("button", { text: "Next →", cls: "pdf-sketch-nav-btn" });

    // ── Drawing toolbar ───────────────────────────────────────────────────────
    const toolbar = contentEl.createDiv({ cls: "pdf-sketch-toolbar" });

    const penBtn = toolbar.createEl("button", { text: "✏ Pen", cls: "pdf-sketch-tool-btn active" });
    const eraserBtn = toolbar.createEl("button", { text: "◻ Eraser", cls: "pdf-sketch-tool-btn" });

    const colorLabel = toolbar.createEl("label", { cls: "pdf-sketch-label", text: "Color " });
    const colorInput = colorLabel.createEl("input", { attr: { type: "color", value: "#000000" } });

    const sizeLabel = toolbar.createEl("label", { cls: "pdf-sketch-label", text: "Size " });
    const sizeInput = sizeLabel.createEl("input", {
      attr: { type: "range", min: "1", max: "30", value: "3" }
    });

    const clearBtn = toolbar.createEl("button", { text: "Clear", cls: "pdf-sketch-tool-btn" });

    // ── Canvas container ──────────────────────────────────────────────────────
    const container = contentEl.createDiv({ cls: "camera-container pdf-sketch-container" });

    // Background canvas – rendered PDF page lives here
    this.bgCanvas = container.createEl("canvas", { cls: "pdf-sketch-bg-canvas" });
    // Drawing canvas – transparent overlay the user draws on
    this.drawCanvas = container.createEl("canvas", { cls: "pdf-sketch-draw-canvas overlay-canvas" });

    // ── Save button ───────────────────────────────────────────────────────────
    const controls = contentEl.createDiv({ cls: "camera-controls" });
    this.saveBtn = controls.createEl("button", { text: "Save & Insert", cls: "mod-cta" });
    const saveBtn = this.saveBtn;

    // ── Wire up event handlers ────────────────────────────────────────────────
    loadBtn.addEventListener("click", async () => {
      const selectedPath = pdfSelect.value;
      if (!selectedPath) {
        new import_obsidian.Notice("Please select a PDF file first.");
        return;
      }
      loadBtn.disabled = true;
      loadBtn.textContent = "Loading…";
      try {
        await this.loadPDF(selectedPath);
      } finally {
        loadBtn.disabled = false;
        loadBtn.textContent = "Load PDF";
      }
    });

    prevBtn.addEventListener("click", async () => {
      if (this.currentPage > 1) {
        this.currentPage--;
        await this.renderPage(this.currentPage);
      }
    });

    nextBtn.addEventListener("click", async () => {
      if (this.currentPage < this.totalPages) {
        this.currentPage++;
        await this.renderPage(this.currentPage);
      }
    });

    penBtn.addEventListener("click", () => {
      this.currentTool = "pen";
      penBtn.classList.add("active");
      eraserBtn.classList.remove("active");
      this.drawCanvas.style.cursor = "crosshair";
    });

    eraserBtn.addEventListener("click", () => {
      this.currentTool = "eraser";
      eraserBtn.classList.add("active");
      penBtn.classList.remove("active");
      this.drawCanvas.style.cursor = "cell";
    });

    colorInput.addEventListener("input", (e) => {
      this.currentColor = e.target.value;
    });

    sizeInput.addEventListener("input", (e) => {
      this.lineWidth = parseInt(e.target.value, 10);
    });

    clearBtn.addEventListener("click", () => {
      const ctx = this.drawCanvas.getContext("2d");
      if (ctx) ctx.clearRect(0, 0, this.drawCanvas.width, this.drawCanvas.height);
    });

    saveBtn.addEventListener("click", () => this.saveSketch());

    // ── Drawing events ────────────────────────────────────────────────────────
    this.setupDrawingEvents();

    // Start with a default blank canvas size
    this.setCanvasSize(800, 600);
  }

  setCanvasSize(width, height) {
    this.bgCanvas.width = width;
    this.bgCanvas.height = height;
    this.drawCanvas.width = width;
    this.drawCanvas.height = height;
    // Fill background white so the canvas isn't transparent
    const ctx = this.bgCanvas.getContext("2d");
    if (ctx) {
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, width, height);
    }
  }

  async ensurePDFJS() {
    if (window.pdfjsLib) return;
    await new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = PDFJS_CDN;
      script.onload = () => {
        window.pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJS_WORKER_CDN;
        resolve();
      };
      script.onerror = () =>
        reject(new Error("Could not load PDF.js. An internet connection is required for the first use."));
      document.head.appendChild(script);
    });
  }

  async ensurePDFLib() {
    if (window.PDFLib) return;
    await new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = PDFLIB_CDN;
      script.onload = resolve;
      script.onerror = () =>
        reject(new Error("Could not load pdf-lib. An internet connection is required for the first use."));
      document.head.appendChild(script);
    });
  }

  async loadPDF(pdfPath) {
    try {
      await this.ensurePDFJS();
    } catch (err) {
      new import_obsidian.Notice(err.message);
      return;
    }

    try {
      const resourceUrl = this.app.vault.adapter.getResourcePath(pdfPath);
      const loadingTask = window.pdfjsLib.getDocument(resourceUrl);
      this.pdfDoc = await loadingTask.promise;
      this.totalPages = this.pdfDoc.numPages;
      this.currentPage = 1;
      this.currentPdfFile = this.app.vault.getAbstractFileByPath(pdfPath);
      this.pageNavEl.classList.remove("hidden");
      if (this.saveBtn) this.saveBtn.textContent = "Save to PDF";
      await this.renderPage(this.currentPage);
    } catch (err) {
      new import_obsidian.Notice("Error loading PDF: " + (err.message || err.toString()));
    }
  }

  async renderPage(pageNum) {
    if (!this.pdfDoc) return;
    try {
      const page = await this.pdfDoc.getPage(pageNum);
      const viewport = page.getViewport({ scale: 1.5 });

      this.setCanvasSize(viewport.width, viewport.height);

      // Clear the drawing layer when navigating pages
      const drawCtx = this.drawCanvas.getContext("2d");
      if (drawCtx) drawCtx.clearRect(0, 0, this.drawCanvas.width, this.drawCanvas.height);

      const ctx = this.bgCanvas.getContext("2d");
      await page.render({ canvasContext: ctx, viewport }).promise;

      this.pageInfoEl.textContent = `Page ${pageNum} / ${this.totalPages}`;
    } catch (err) {
      new import_obsidian.Notice("Error rendering page: " + (err.message || err.toString()));
    }
  }

  setupDrawingEvents() {
    const getPos = (e) => {
      const rect = this.drawCanvas.getBoundingClientRect();
      const scaleX = this.drawCanvas.width / rect.width;
      const scaleY = this.drawCanvas.height / rect.height;
      const src = e.touches ? e.touches[0] : e;
      return {
        x: (src.clientX - rect.left) * scaleX,
        y: (src.clientY - rect.top) * scaleY,
      };
    };

    const onStart = (e) => {
      if (e.touches) e.preventDefault();
      this.isDrawing = true;
      const pos = getPos(e);
      this.lastX = pos.x;
      this.lastY = pos.y;
    };

    const onMove = (e) => {
      if (!this.isDrawing) return;
      if (e.touches) e.preventDefault();
      const ctx = this.drawCanvas.getContext("2d");
      if (!ctx) return;
      const pos = getPos(e);
      ctx.beginPath();
      ctx.moveTo(this.lastX, this.lastY);
      ctx.lineTo(pos.x, pos.y);
      if (this.currentTool === "eraser") {
        ctx.globalCompositeOperation = "destination-out";
        ctx.strokeStyle = "rgba(0,0,0,1)";
        ctx.lineWidth = this.lineWidth * 3;
      } else {
        ctx.globalCompositeOperation = "source-over";
        ctx.strokeStyle = this.currentColor;
        ctx.lineWidth = this.lineWidth;
      }
      ctx.lineCap = "round";
      ctx.lineJoin = "round";
      ctx.stroke();
      this.lastX = pos.x;
      this.lastY = pos.y;
    };

    const onEnd = () => {
      this.isDrawing = false;
    };

    this.drawCanvas.addEventListener("mousedown", onStart);
    this.drawCanvas.addEventListener("mousemove", onMove);
    this.drawCanvas.addEventListener("mouseup", onEnd);
    this.drawCanvas.addEventListener("mouseleave", onEnd);
    this.drawCanvas.addEventListener("touchstart", onStart, { passive: false });
    this.drawCanvas.addEventListener("touchmove", onMove, { passive: false });
    this.drawCanvas.addEventListener("touchend", onEnd);
  }

  async saveSketch() {
    if (!this.currentPdfFile) {
      new import_obsidian.Notice("No PDF loaded. Please load a PDF first.");
      return;
    }

    // Export only the drawing layer as a transparent PNG
    const sketchBytes = await new Promise((resolve, reject) => {
      this.drawCanvas.toBlob((blob) => {
        if (!blob) { reject(new Error("Failed to export sketch.")); return; }
        blob.arrayBuffer().then(resolve).catch(reject);
      }, "image/png");
    });

    try {
      await this.ensurePDFLib();
    } catch (err) {
      new import_obsidian.Notice(err.message);
      return;
    }

    try {
      const { PDFDocument } = window.PDFLib;

      // Load original PDF bytes from vault
      const originalBytes = await this.app.vault.readBinary(this.currentPdfFile);
      const pdfLibDoc = await PDFDocument.load(originalBytes);

      // Embed sketch PNG (transparent where no ink)
      const pngImage = await pdfLibDoc.embedPng(sketchBytes);

      // Stretch PNG over the full page (PDF coordinates: origin = bottom-left)
      const page = pdfLibDoc.getPage(this.currentPage - 1);
      const { width, height } = page.getSize();
      page.drawImage(pngImage, { x: 0, y: 0, width, height });

      // Overwrite the original file in the vault
      const savedBytes = await pdfLibDoc.save();
      await this.app.vault.modifyBinary(this.currentPdfFile, savedBytes.buffer);

      new import_obsidian.Notice("Sketch saved to PDF!");
      this.close();
    } catch (err) {
      new import_obsidian.Notice("Error saving to PDF: " + (err.message || err.toString()));
    }
  }

  onClose() {
    this.contentEl.empty();
  }
};
